// Generated by IB v0.8.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <AppKit/AppKit.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreServices/CoreServices.h>
#import <Foundation/Foundation.h>
#import <Security/Security.h>
#import <SystemConfiguration/SystemConfiguration.h>

@interface AppDelegate: NSObject <NSApplicationDelegate>
-(IBAction) applicationDidFinishLaunching:(id) notification;
-(IBAction) process_sensor:(id) notification;
-(IBAction) setup_observers;
-(IBAction) handle_error:(id) notification;
-(IBAction) setup_defaults;
-(IBAction) process_attach:(id) notification;
-(IBAction) buildWindow;

@end

@interface ButtonWindowController: NSWindowController

@property IBOutlet NSTextField * ip_field;
@property IBOutlet NSTextField * port_field;
@property IBOutlet NSTextField * phidget_west_field;
@property IBOutlet NSTextField * phidget_east_field;
@property IBOutlet NSTextField * phidget_south_field;
@property IBOutlet NSTextField * west_0_threshold_field;
@property IBOutlet NSTextField * west_4_threshold_field;
@property IBOutlet NSTextField * west_7_threshold_field;
@property IBOutlet NSTextField * east_0_threshold_field;
@property IBOutlet NSTextField * east_4_threshold_field;
@property IBOutlet NSTextField * east_7_threshold_field;
@property IBOutlet NSTextField * south_0_threshold_field;
@property IBOutlet NSTextField * south_4_threshold_field;
@property IBOutlet NSTextField * south_7_threshold_field;

-(IBAction) save_values:(id) sender;
-(IBAction) setup_window;
-(IBAction) setup_notifications;

@end

@interface HTTPSender: NSObject
-(IBAction) initialize:(id) params;
-(IBAction) simple_get;

@end

